apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: echo=oroncohen/echo
    argocd-image-updater.argoproj.io/echo.helm.image-name: app.image
    argocd-image-updater.argoproj.io/echo.helm.image-tag: app.tag
    argocd-image-updater.argoproj.io/echo.update-strategy: semver:~1.0
    #argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default
  source:
    repoURL: https://github.com/MaybeOron/echoArgo.git
    targetRevision: HEAD
    path: echo
  
    helm:
      # valueFiles:
      # - values.yaml
      
      values: |
        issuer:
          email: oronboy100@gmail.com
        app:
          image: oroncohen/echo
          namespace: prod
          name: echo-prod
          tag: 1.0.8
          replicas: 2
          resources:
            limits:
              memory: "200Mi"
              cpu: "300m"
            requests:
              memory: "100Mi"
              cpu: "200m"
        domain:
          url: prod.oronargo.tk
        replicaCount: 1
        port: 3000
        
  
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
   # - PruneLast=true