apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-yaml
  namespace: default
  labels:
      app: echo-yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-yaml
  template:
    metadata:
      labels:
        app: echo-yaml
    spec:
      containers:
      - name: echo-yaml
        image: avitaltamirdeveleap/echo
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-yaml-lb
spec:
  type: LoadBalancer
  selector:
    app: echo-yaml
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
