app:
  namespace: default
  replicas: 2
  name: echo-yaml
  image: oroncohen/echo
  tag: 1.0.0
  port: 3000
  resources:
    limits:
      memory: "200Mi"
      cpu: "300m"
    requests:
      memory: "100Mi"
      cpu: "200m"

domain:
  url: oronargo.tk

issuer:
  email: oronboy100@gmail.com

# mongodb:
#   enabled: true
#   auth:
#     username: "mongo"
#     password: "mongo"
#     database: "echodb"
